{
    "data": [
        {
            "test_name": "mantidqt_qt5.test_sliceviewer_model.test_sliceviewer_model",
            "latest_failed_build": "4479",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 2,
            "past_outcome": {
                "build_keys": [
                    "4482",
                    "4481",
                    "4480",
                    "4479",
                    "4478",
                    "4477",
                    "4476",
                    "4475",
                    "4474",
                    "4473",
                    "4472",
                    "4471",
                    "4470",
                    "4469",
                    "4468",
                    "4467",
                    "4466",
                    "4465",
                    "4464",
                    "4463",
                    "4462",
                    "4461",
                    "4460",
                    "4459",
                    "4458",
                    "4457",
                    "4456",
                    "4455",
                    "4454",
                    "4453"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "None",
                    "Failed",
                    "Failed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "mantidqt_qt5.test_sliceviewer_model.test_sliceviewer_model",
                "build": "4479",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "17.01",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.7.20230713.1348.dev3\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n.....E.......E.E................................\n======================================================================\nERROR: test_MDH_workspace_in_hkl_supports_non_orthogonal_axes (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 405, in test_MDH_workspace_in_hkl_supports_non_orthogonal_axes\n    self._assert_supports_non_orthogonal_axes(\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 921, in _assert_supports_non_orthogonal_axes\n    model = SliceViewerModel(_create_mock_workspace(ws_type, coords, has_oriented_lattice))\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 84, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 574, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in get_proj_matrix\n    proj_matrix = self.projection_matrix_from_basis(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 544, in projection_matrix_from_basis\n    proj_matrix[: qmask.sum(), : qmask.sum()] = basis_matrix[qmask, :][:, qflags]\nValueError: could not broadcast input array from shape (0,2) into shape (0,0)\n\n======================================================================\nERROR: test_calculate_axes_angles_uses_basis_vectors_even_if_WMatrix_log_available_MDHisto (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 508, in test_calculate_axes_angles_uses_basis_vectors_even_if_WMatrix_log_available_MDHisto\n    model = SliceViewerModel(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 84, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 574, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in get_proj_matrix\n    proj_matrix = self.projection_matrix_from_basis(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 544, in projection_matrix_from_basis\n    proj_matrix[: qmask.sum(), : qmask.sum()] = basis_matrix[qmask, :][:, qflags]\nValueError: could not broadcast input array from shape (0,2) into shape (0,0)\n\n======================================================================\nERROR: test_calculate_axes_angles_uses_identity_if_W_unavailable_MDHisto (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 531, in test_calculate_axes_angles_uses_identity_if_W_unavailable_MDHisto\n    model = SliceViewerModel(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 84, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 574, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in get_proj_matrix\n    proj_matrix = self.projection_matrix_from_basis(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 544, in projection_matrix_from_basis\n    proj_matrix[: qmask.sum(), : qmask.sum()] = basis_matrix[qmask, :][:, qflags]\nValueError: could not broadcast input array from shape (0,2) into shape (0,0)\n\n----------------------------------------------------------------------\nRan 48 tests in 4.087s\n\nFAILED (errors=3)\n\n          Start  793: CurveFittingTest_StaticKuboToyabeTimesExpDecayTest\n"
            }
        }
    ]
}