{
    "data": [
        {
            "test_name": "CrystalTest_PeakIntensityVsRadiusTest",
            "latest_failed_build": "1910",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "CrystalTest_PeakIntensityVsRadiusTest",
                "build": "1910",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.84",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nRunning 7 testsCreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.02 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.01 seconds\n.CreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.01 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.01 seconds\nPeakIntensityVsRadius-[Notice] PeakIntensityVsRadius started\nSegmentation fault\n\n          Start  280: AlgorithmsTest_ExtractMaskTest\n"
            }
        },
        {
            "test_name": "MDAlgorithmsTest_IntegratePeaksMD2Test",
            "latest_failed_build": "1910",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MDAlgorithmsTest_IntegratePeaksMD2Test",
                "build": "1910",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.55",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nRunning 30 tests.CreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nLogger_simpleRun-[Notice] Running simpleRun with inputs: shouldPass:1 numberValuesPeakRadius:1 numberValuesBkgInnerRadius:1 numberValuesBkgOuterRadius:1 cyl:0 ellip:0\nIntegratePeaksMD-[Notice] IntegratePeaksMD started\nIntegratePeaksMD-[Error] Can&#x27;t execute MaskBTP algorithm for this instrument to set edge for IntegrateIfOnEdge option\nSegmentation fault\n\n          Start 1595: python.algorithms.VelocityAutoCorrelationsTest.VelocityAutoCorrelationsTest\n"
            }
        },
        {
            "test_name": "python.algorithms.HB3AIntegratePeaksTest.HB3AIntegratePeaksTest",
            "latest_failed_build": "1910",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.algorithms.HB3AIntegratePeaksTest.HB3AIntegratePeaksTest",
                "build": "1910",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "31.42",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nHB3AAdjustSampleNorm-[Notice] HB3AAdjustSampleNorm started\nLoadMD-[Notice] LoadMD started (child)\nLoadMD-[Notice] LoadMD successful, Duration 13.44 seconds\nSetGoniometer-[Notice] SetGoniometer started (child)\nSetGoniometer-[Notice] SetGoniometer successful, Duration 0.00 seconds\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE started (child)\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE successful, Duration 1.11 seconds\nDeleteWorkspace-[Notice] DeleteWorkspace started (child)\nDeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds\nLoadMD-[Notice] LoadMD started (child)\nLoadMD-[Notice] LoadMD successful, Duration 9.37 seconds\nSetGoniometer-[Notice] SetGoniometer started (child)\nSetGoniometer-[Notice] SetGoniometer successful, Duration 0.00 seconds\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE started (child)\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE successful, Duration 1.19 seconds\nDeleteWorkspace-[Notice] DeleteWorkspace started (child)\nDeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds\nMergeMD-[Notice] MergeMD started (child)\nMergeMD-[Notice] MergeMD successful, Duration 0.14 seconds\nDeleteWorkspaces-[Notice] DeleteWorkspaces started (child)\nDeleteWorkspaces-[Notice] DeleteWorkspaces successful, Duration 0.00 seconds\nHB3AAdjustSampleNorm-[Notice] HB3AAdjustSampleNorm successful, Duration 25.69 seconds\nHB3AFindPeaks-[Notice] HB3AFindPeaks started\nFindPeaksMD-[Notice] FindPeaksMD started (child)\nFindPeaksMD-[Notice] Number of peaks found: 26\nFindPeaksMD-[Notice] FindPeaksMD successful, Duration 0.01 seconds\nFindUBUsingFFT-[Notice] FindUBUsingFFT started (child)\nFindUBUsingFFT-[Notice] Error = 0.0173407\nFindUBUsingFFT-[Notice] UB = Matrix(3,3)0.0223361,0.0484886,-0.100805,-0.275231,0.0340218,0.00952149,0.0372822,0.267584,-0.00227044\nFindUBUsingFFT-[Notice] New UB will index 24 Peaks out of 26 with tolerance of  0.15\nFindUBUsingFFT-[Notice] Lattice Parameters:    3.645732    3.714062   10.206437   79.318951   79.944046   89.376487   133.686337\nFindUBUsingFFT-[Notice] Parameter Errors  :    0.009246    0.008566    0.021181    0.170299    0.181964    0.196921    0.546722\nFindUBUsingFFT-[Notice] FindUBUsingFFT successful, Duration 0.45 seconds\nShowPossibleCells-[Notice] ShowPossibleCells started (child)\nShowPossibleCells-[Notice] Num Cells : 6\nShowPossibleCells-[Notice] Form #15  Error: 0.0683  Tetragonal    I   Lat Par:   3.6457   3.7141  19.7478    90.086   89.646   89.376     267.37\nShowPossibleCells-[Notice] Form #16  Error: 0.1698  Orthorhombic  F   Lat Par:   5.2326   5.1760  19.7478    89.689   90.185   88.936     534.75\nShowPossibleCells-[Notice] Form #42  Error: 0.0284  Orthorhombic  I   Lat Par:   3.6457   3.7141  19.7478    89.914   90.354   89.376     267.37\nShowPossibleCells-[Notice] Form #10  Error: 0.0683  Monoclinic    C   Lat Par:   5.2326   5.1760  10.2064    89.427  104.668   91.064     267.37\nShowPossibleCells-[Notice] Form #37  Error: 0.0284  Monoclinic    I   Lat Par:   3.7141   3.6457  19.7478    89.646   89.914   90.624     267.37\nShowPossibleCells-[Notice] Form #31  Error: 0.0000  Triclinic     P   Lat Par:   3.6457   3.7141  10.2064    79.319   79.944   89.376     133.69\nShowPossibleCells-[Notice] ShowPossibleCells successful, Duration 0.00 seconds\nSelectCellOfType-[Notice] SelectCellOfType started (child)\nSelectCellOfType-[Notice] Form #16  Error: 0.1698  Orthorhombic  F   Lat Par:   5.2326   5.1760  19.7478    89.689   90.185   88.936     534.75\nSelectCellOfType-[Notice] Reduced to Conventional Cell Transformation Matrix =  -1 -1 0 1 -1 0 1 1 2 \nSelectCellOfType-[Notice] Re-indexed the peaks with the new UB. \nSelectCellOfType-[Notice] Now, 24 are indexed with average error 0.0194414\nSelectCellOfType-[Notice] SelectCellOfType successful, Duration 0.00 seconds\nOptimizeLatticeForCellType-[Notice] OptimizeLatticeForCellType started (child)\nOptimizeLatticeForCellType-[Notice] peaks  Lattice Parameters:    5.234869    5.257473   19.748138   90.000000   90.000000   90.000000   543.511918\nOptimizeLatticeForCellType-[Notice] Parameter Errors  :    0.004353    0.009826    0.013286    0.000000    0.000000    0.000000    1.170370\nIndexPeaks-[Notice] Run 183 indexed 10 peaks out of 11 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.0177215\nIndexPeaks-[Notice] Run 182 indexed 14 peaks out of 15 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.0192002\nIndexPeaks-[Notice] All runs indexed 24 peaks out of 26 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.0185841\nIndexPeaks-[Notice] Lattice Parameters:    5.234869    5.257473   19.748138   90.000000   90.000000   90.000000   543.511918\nIndexPeaks-[Notice] Parameter Errors  :    0.004353    0.009826    0.013286    0.000000    0.000000    0.000000    1.170370\nOptimizeLatticeForCellType-[Notice] OptimizeLatticeForCellType successful, Duration 0.00 seconds\nHB3AFindPeaks-[Notice] HB3AFindPeaks successful, Duration 0.48 seconds\nIntegratePeaksMD-[Notice] IntegratePeaksMD started\nMaskBTP-[Error] Error in execution of algorithm MaskBTP:\nMaskBTP-[Error] Instrument &#x27;HB3A&#x27; not in the allowed list\nMaskBTP-[Error]   at line 94 in &#x27;/jenkins_workdir/workspace/pull_requests-conda-linux/Framework/PythonInterface/plugins/algorithms/MaskBTP.py&#x27;\nIntegratePeaksMD-[Error] Can&#x27;t execute MaskBTP algorithm for this instrument to set edge for IntegrateIfOnEdge option\nSegmentation fault\n\n          Start 1312: NexusGeometryTest_NexusGeometrySaveTest\n"
            }
        },
        {
            "test_name": "python.MuonQt5.tf_asymmetry_fitting_options_view_test.tf_asymmetry_fitting_options_view_test",
            "latest_failed_build": "1909",
            "agent_name": "Linux",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 2,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.MuonQt5.tf_asymmetry_fitting_options_view_test.tf_asymmetry_fitting_options_view_test",
                "build": "1909",
                "agent_name": "Linux",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "0.90",
                "stacktrace": "QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to &#x27;/tmp/runtime-abc&#x27;\nlibEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)\nlibEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)\nlibEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)\nlibEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)\n.EEEEEEE\n======================================================================\nERROR: test_that_hide_normalisation_options_will_hide_all_of_the_tf_asymmetry_options (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_is_normalisation_fixed_can_be_set_to_true (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_set_tf_asymmetry_mode_will_hide_the_tf_asymmetry_options_when_set_to_false (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_set_tf_asymmetry_mode_will_show_the_tf_asymmetry_options_when_set_to_true (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_show_normalisation_options_will_show_all_of_the_tf_asymmetry_options (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_normalisation_can_be_set_as_expected (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_has_been_initialized_with_a_normalisation_line_edit_which_has_a_validator (tf_asymmetry_fitting_options_view_test.TFAsymmetryFittingOptionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;TFAsymmetryFittingOptionsView&#x27; object has no attribute &#x27;showEvent&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: &lt;class &#x27;PyQt5.QtCore.QMetaObject&#x27;&gt; returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view_test.py&quot;, line 20, in setUp\n    self.view = TFAsymmetryFittingOptionsView()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py&quot;, line 23, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 44, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n----------------------------------------------------------------------\nRan 8 tests in 0.055s\n\nFAILED (errors=7)\n\n          Start 2190: python.MuonQt5.tf_asymmetry_fitting_options_view_test.tf_asymmetry_fitting_options_view_test\n"
            }
        },
        {
            "test_name": "python.SANS.command_interface.command_interface_state_director_test.command_interface_state_director_test",
            "latest_failed_build": "1905",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 4,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.SANS.command_interface.command_interface_state_director_test.command_interface_state_director_test",
                "build": "1905",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "1.42",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.922\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nE.\n======================================================================\nERROR: test_can_set_commands_without_exceptions (command_interface_state_director_test.CommandInterfaceStateDirectorTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/SANS/command_interface/command_interface_state_director_test.py&quot;, line 118, in test_can_set_commands_without_exceptions\n    state = command_interface.process_commands()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/SANS/sans/command_interface/command_interface_state_director.py&quot;, line 161, in process_commands\n    state = self._process_command_queue()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/SANS/sans/command_interface/command_interface_state_director.py&quot;, line 274, in _process_command_queue\n    process_function(command)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/SANS/sans/command_interface/command_interface_state_director.py&quot;, line 603, in _process_qxy_limit\n    new_state_entries = {LimitsId.QXY: simple_range(start=q_min, stop=q_max, step=q_step)}\nTypeError: __new__() missing 1 required positional argument: &#x27;step_type&#x27;\n\n----------------------------------------------------------------------\nRan 2 tests in 0.291s\n\nFAILED (errors=1)\n\n          Start 2023: mantidqt_qt5.test_observing_view.test_observing_view\n"
            }
        },
        {
            "test_name": "mantidqt_qt5.test_cut_representation.test_cut_representation",
            "latest_failed_build": "1891",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 2,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "mantidqt_qt5.test_cut_representation.test_cut_representation",
                "build": "1891",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.35",
                "stacktrace": "EEEEEEEEEEEE\n======================================================================\nERROR: test_get_mid_point (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_get_perp_dir (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_get_start_end_points (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_has_current_artist (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_is_valid_event_if_event_in_axes (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_is_valid_event_if_event_not_in_axes (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_motion_end_point_selected (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_motion_midpoint_selected (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_motion_thickness_selected (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_release_not_notify_if_no_current_artist (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_release_not_notify_if_not_valid_event (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n======================================================================\nERROR: test_on_release_swaps_start_end_so_xmin_less_than_xmax (test_cut_representation.LinePlotsTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer//representation/test/test_cut_representation.py&quot;, line 23, in setUp\n    self.cut_rep = CutRepresentation(self.canvas, self.notify_on_release, xmin, xmax, ymin, ymax, thickness)\nTypeError: __init__() missing 1 required positional argument: &#x27;transform&#x27;\n\n----------------------------------------------------------------------\nRan 12 tests in 0.020s\n\nFAILED (errors=12)\n\n          Start 1515: python.algorithms.FractionalIndexingTest.FractionalIndexingTest\n"
            }
        },
        {
            "test_name": "mantidqt_qt5.test_sliceviewer_presenter.test_sliceviewer_presenter",
            "latest_failed_build": "1891",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "mantidqt_qt5.test_sliceviewer_presenter.test_sliceviewer_presenter",
                "build": "1891",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "3.18",
                "stacktrace": ".........F...F.......................\n======================================================================\nFAIL: test_cut_view_toggled_on (test_sliceviewer_presenter.SliceViewerTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py&quot;, line 331, in test_cut_view_toggled_on\n    self.view.data_view.deactivate_and_disable_tool.assert_has_calls([mock.call(tool) for tool in\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 950, in assert_has_calls\n    raise AssertionError(\nAssertionError: Calls not found.\nExpected: [call(&#x27;RegionSelection&#x27;), call(&#x27;LinePlots&#x27;), call(&#x27;NonOrthogonalAxes&#x27;)]\nActual: [call(&#x27;RegionSelection&#x27;), call(&#x27;LinePlots&#x27;)]\n\n======================================================================\nFAIL: test_non_orthogonal_axes_toggled_off (test_sliceviewer_presenter.SliceViewerTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py&quot;, line 292, in test_non_orthogonal_axes_toggled_off\n    data_view_mock.enable_tool_button.assert_has_calls(\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 950, in assert_has_calls\n    raise AssertionError(\nAssertionError: Calls not found.\nExpected: [call(&#x27;LinePlots&#x27;), call(&#x27;RegionSelection&#x27;), call(&#x27;NonAxisAlignedCuts&#x27;)]\nActual: [call(&#x27;LinePlots&#x27;), call(&#x27;RegionSelection&#x27;)]\n\n----------------------------------------------------------------------\nRan 37 tests in 1.089s\n\nFAILED (failures=2)\n\n          Start  989: DataHandlingTest_SaveNXTomoTest\n"
            }
        },
        {
            "test_name": "python.SANS.user_file.txt_parsers.toml_v1_parser_test.toml_v1_parser_test",
            "latest_failed_build": "1889",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1910",
                    "1909",
                    "1908",
                    "1907",
                    "1906",
                    "1905",
                    "1904",
                    "1903",
                    "1902",
                    "1901",
                    "1900",
                    "1899",
                    "1898",
                    "1897",
                    "1896",
                    "1895",
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.SANS.user_file.txt_parsers.toml_v1_parser_test.toml_v1_parser_test",
                "build": "1889",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.82",
                "stacktrace": ".SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nESANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n..SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\nSANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n..\n======================================================================\nERROR: test_binning_commands_parsed (toml_v1_parser_test.TomlV1ParserTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/scripts/test/SANS/user_file/toml_parsers/toml_v1_parser_test.py&quot;, line 180, in test_binning_commands_parsed\n    self.assertTrue(two_d_convert_to_q.q_xy_step_type is RangeStepType.LIN)\nAttributeError: &#x27;StateConvertToQ&#x27; object has no attribute &#x27;q_xy_step_type&#x27;\n\n----------------------------------------------------------------------\nRan 29 tests in 0.212s\n\nFAILED (errors=1)\n\n          Start 1749: PythonInterfaceCppTest_RunPythonScriptTest\n"
            }
        }
    ]
}