{
    "data": [
        {
            "test_name": "python.algorithms.AbinsAdvancedParametersTest.AbinsAdvancedParametersTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.algorithms.AbinsAdvancedParametersTest.AbinsAdvancedParametersTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "6.98",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.7.20230721.1726.dev25\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nPython-[Warning] Failed to load plugin /Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins.py.\nError: Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 189, in load_from_file\n    name, module = load_plugin(filepath)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 210, in load_plugin\n    module = loader.run()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 49, in run\n    return SourceFileLoader(name, pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins.py&quot;, line 17, in &lt;module&gt;\n    from abins.abinsalgorithm import AbinsAlgorithm\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/abinsalgorithm.py&quot;, line 21, in &lt;module&gt;\n    from abins.instruments import get_instrument, Instrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\nPython-[Warning] Failed to load plugin /Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins2D.py.\nError: Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 189, in load_from_file\n    name, module = load_plugin(filepath)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 210, in load_plugin\n    module = loader.run()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 49, in run\n    return SourceFileLoader(name, pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins2D.py&quot;, line 18, in &lt;module&gt;\n    from abins.abinsalgorithm import AbinsAlgorithm\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/abinsalgorithm.py&quot;, line 21, in &lt;module&gt;\n    from abins.instruments import get_instrument, Instrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\nFEFFFFFFFFFFF.FFFFF\n======================================================================\nERROR: test_good_case (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 303, in test_good_case\n    Abins(VibrationalOrPhononFile=self._Si2 + &quot;.phonon&quot;, OutputWorkspace=self._wrk_name)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nFAIL: test_doubled_name (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 199, in test_doubled_name\n    self.assertRaisesRegex(\nAssertionError: &quot;Name for powder_data_group already used by as name of another folder.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_crystal_data_group (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 172, in test_wrong_crystal_data_group\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of crystal_data_group&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_dft_group (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 142, in test_wrong_dft_group\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid name for folder in which the ab initio data should be stored.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_energy_window (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 241, in test_wrong_energy_window\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid energy window for rebinning.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_fwhm (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 65, in test_wrong_fwhm\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of fwhm&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_max_wavenumber (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 229, in test_wrong_max_wavenumber\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of max_wavenumber&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_min_wavenumber (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 214, in test_wrong_min_wavenumber\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of min_wavenumber&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_optimal_size (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 282, in test_wrong_optimal_size\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of optimal_size&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_powder_data_group (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 157, in test_wrong_powder_data_group\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of powder_data_group&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_powder_s_data_group (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 187, in test_wrong_powder_s_data_group\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of s_data_group&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_s_absolute_threshold (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 254, in test_wrong_s_absolute_threshold\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of s_absolute_threshold&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_s_relative_threshold (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 267, in test_wrong_s_relative_threshold\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of s_relative_threshold&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_tosca_cos_scattering_angle (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 95, in test_wrong_tosca_cos_scattering_angle\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of cosines scattering angle for TOSCA&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_tosca_final_energy (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 79, in test_wrong_tosca_final_energy\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of final_neutron_energy for TOSCA&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_tosca_resolution_constant_A (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 106, in test_wrong_tosca_resolution_constant_A\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of constant A for TOSCA&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_tosca_resolution_constant_B (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 116, in test_wrong_tosca_resolution_constant_B\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of constant B for TOSCA&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_tosca_resolution_constant_C (AbinsAdvancedParametersTest.AbinsAdvancedParametersTest)\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py&quot;, line 126, in test_wrong_tosca_resolution_constant_C\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid value of constant C for TOSCA&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n----------------------------------------------------------------------\nRan 19 tests in 0.014s\n\nFAILED (failures=17, errors=1)\n\n          Start  174: AlgorithmsTest_CalculateFlatBackgroundTest\n"
            }
        },
        {
            "test_name": "python.algorithms.AbinsBasicTest.AbinsBasicTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.algorithms.AbinsBasicTest.AbinsBasicTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "6.04",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.7.20230721.1726.dev25\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nPython-[Warning] Failed to load plugin /Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins.py.\nError: Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 189, in load_from_file\n    name, module = load_plugin(filepath)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 210, in load_plugin\n    module = loader.run()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 49, in run\n    return SourceFileLoader(name, pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins.py&quot;, line 17, in &lt;module&gt;\n    from abins.abinsalgorithm import AbinsAlgorithm\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/abinsalgorithm.py&quot;, line 21, in &lt;module&gt;\n    from abins.instruments import get_instrument, Instrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\nPython-[Warning] Failed to load plugin /Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins2D.py.\nError: Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 189, in load_from_file\n    name, module = load_plugin(filepath)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 210, in load_plugin\n    module = loader.run()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/kernel/plugins.py&quot;, line 49, in run\n    return SourceFileLoader(name, pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/Abins2D.py&quot;, line 18, in &lt;module&gt;\n    from abins.abinsalgorithm import AbinsAlgorithm\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/abinsalgorithm.py&quot;, line 21, in &lt;module&gt;\n    from abins.instruments import get_instrument, Instrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\nFEFEEEEEFEFEFEEEEEEEFE\n======================================================================\nERROR: test_atom_index_invalid (AbinsBasicTest.AbinsBasicTest)\nIf the atoms field includes an unmatched entry (i.e. containing the prefix but not matching the &#x27;\\d+&#x27; regex,\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_atom_index_limits (AbinsBasicTest.AbinsBasicTest)\nIndividual atoms may be indexed (counting from 1); if the index falls outside number of atoms, Abins should\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_exp (AbinsBasicTest.AbinsBasicTest)\nTests if experimental data is loaded correctly.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 267, in test_exp\n    Abins(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nERROR: test_exp (AbinsBasicTest.AbinsBasicTest)\nTests if experimental data is loaded correctly.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_lagrange_exists (AbinsBasicTest.AbinsBasicTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 247, in test_lagrange_exists\n    Abins(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nERROR: test_lagrange_exists (AbinsBasicTest.AbinsBasicTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_non_existing_atoms (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which  a user requests to create workspaces for atoms which do not exist in the system.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_non_unique_atoms (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which a user specifies non-unique atoms (for example &quot;atom_1,atom_2,atom1&quot;).\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_non_unique_elements (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which a user specifies non-unique elements (for example in squaricn that would be &quot;C,C,H&quot;).\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_partial_by_element (AbinsBasicTest.AbinsBasicTest)\nCheck results of INS spectrum resolved by elements: default should match explicit list of elements\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 295, in test_partial_by_element\n    wrk_ref = Abins(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nERROR: test_partial_by_element (AbinsBasicTest.AbinsBasicTest)\nCheck results of INS spectrum resolved by elements: default should match explicit list of elements\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_partial_by_number (AbinsBasicTest.AbinsBasicTest)\nSimulated INS spectrum can also be resolved by numbered atoms. Check consistency with element totals\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 346, in test_partial_by_number\n    wrk_ref = Abins(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nERROR: test_partial_by_number (AbinsBasicTest.AbinsBasicTest)\nSimulated INS spectrum can also be resolved by numbered atoms. Check consistency with element totals\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_scale (AbinsBasicTest.AbinsBasicTest)\nTest if scaling is correct.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 213, in test_scale\n    wrk_ref = Abins(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/mantid/simpleapi.py&quot;, line 1206, in fake_function\n    raise RuntimeError(\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\n======================================================================\nERROR: test_scale (AbinsBasicTest.AbinsBasicTest)\nTest if scaling is correct.\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nERROR: test_wrong_input (AbinsBasicTest.AbinsBasicTest)\nTest if the correct behaviour of algorithm in case input is not valid\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 36, in tearDown\n    abins.test_helpers.remove_output_files(\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;test_helpers&#x27;\n\n======================================================================\nFAIL: test_atom_index_invalid (AbinsBasicTest.AbinsBasicTest)\nIf the atoms field includes an unmatched entry (i.e. containing the prefix but not matching the &#x27;\\d+&#x27; regex,\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 191, in test_atom_index_invalid\n    self.assertRaisesRegex(\nAssertionError: &quot;Not all user atom selections \\(&#x27;atoms&#x27; option\\) were understood.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_atom_index_limits (AbinsBasicTest.AbinsBasicTest)\nIndividual atoms may be indexed (counting from 1); if the index falls outside number of atoms, Abins should\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 170, in test_atom_index_limits\n    self.assertRaisesRegex(\nAssertionError: &quot;Invalid user atom selection \\(by number\\) &#x27;atom0&#x27;&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_non_existing_atoms (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which  a user requests to create workspaces for atoms which do not exist in the system.\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 157, in test_non_existing_atoms\n    self.assertRaisesRegex(\nAssertionError: &quot;User defined atom selection \\(by element\\) &#x27;N&#x27;: not present in the system.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_non_unique_atoms (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which a user specifies non-unique atoms (for example &quot;atom_1,atom_2,atom1&quot;).\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 143, in test_non_unique_atoms\n    self.assertRaisesRegex(\nAssertionError: &quot;User atom selection \\(by number\\) contains repeated atom.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_non_unique_elements (AbinsBasicTest.AbinsBasicTest)\nTest scenario in which a user specifies non-unique elements (for example in squaricn that would be &quot;C,C,H&quot;).\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 130, in test_non_unique_elements\n    self.assertRaisesRegex(\nAssertionError: &quot;User atom selection \\(by symbol\\) contains repeated species.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n======================================================================\nFAIL: test_wrong_input (AbinsBasicTest.AbinsBasicTest)\nTest if the correct behaviour of algorithm in case input is not valid\n----------------------------------------------------------------------\nRuntimeError: Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py&quot;, line 55, in test_wrong_input\n    self.assertRaisesRegex(\nAssertionError: &quot;The third line should include &#x27;Number of branches&#x27;.&quot; does not match &quot;Mantid import error. The mock simple API functions have not been replaced! This is an error in the core setup logic of the mantid module, please contact the development team.&quot;\n\n----------------------------------------------------------------------\nRan 11 tests in 0.007s\n\nFAILED (failures=6, errors=16)\n\n          Start 1601: python.algorithms.PEARLTransfitTest.PEARLTransfitTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsAtomsDataTest.AbinsAtomsDataTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsAtomsDataTest.AbinsAtomsDataTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.52",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsAtomsDataTest.py&quot;, line 13, in &lt;module&gt;\n    from abins import AtomsData\nImportError: cannot import name &#x27;AtomsData&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start 2304: python.DNSReductionQt5.dns_file_test.dns_file_test\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsBroadeningTest.AbinsBroadeningTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsBroadeningTest.AbinsBroadeningTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "1.69",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsBroadeningTest.py&quot;, line 13, in &lt;module&gt;\n    from abins.instruments import broadening\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\n          Start  101: KernelTest_PropertyWithValueTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsCalculateQToscaTest.AbinsCalculateQToscaTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsCalculateQToscaTest.AbinsCalculateQToscaTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "2.26",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsCalculateQToscaTest.py&quot;, line 13, in &lt;module&gt;\n    import abins.instruments\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\n          Start 1434: python.api.WorkspaceHistoryTest.WorkspaceHistoryTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsCalculateSPowderTest.AbinsCalculateSPowderTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsCalculateSPowderTest.AbinsCalculateSPowderTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.49",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsCalculateSPowderTest.py&quot;, line 16, in &lt;module&gt;\n    from abins import AbinsData\nImportError: cannot import name &#x27;AbinsData&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start 1384: python.geometry.ComponentInfoTest.ComponentInfoTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsDataTest.AbinsDataTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsDataTest.AbinsDataTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.95",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsDataTest.py&quot;, line 17, in &lt;module&gt;\n    from abins.input import all_loaders\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start   86: KernelTest_NDRandomNumberGeneratorTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsFrequencyPowderGeneratorTest.AbinsFrequencyPowderGeneratorTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsFrequencyPowderGeneratorTest.AbinsFrequencyPowderGeneratorTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.59",
                "stacktrace": "EE\n======================================================================\nERROR: test_construct_freq_combinations (AbinsFrequencyPowderGeneratorTest.FrequencyPowderGeneratorTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsFrequencyPowderGeneratorTest.py&quot;, line 18, in setUp\n    self.simple_freq_generator = abins.FrequencyPowderGenerator\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\n======================================================================\nERROR: test_frequency_generator_larger_numbers (AbinsFrequencyPowderGeneratorTest.FrequencyPowderGeneratorTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsFrequencyPowderGeneratorTest.py&quot;, line 18, in setUp\n    self.simple_freq_generator = abins.FrequencyPowderGenerator\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\n----------------------------------------------------------------------\nRan 2 tests in 0.001s\n\nFAILED (errors=2)\n\n          Start 1663: python.WorkflowAlgorithms.ReflectometryILL_commonTest.ReflectometryILL_commonTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsIOmoduleTest.AbinsIOmoduleTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsIOmoduleTest.AbinsIOmoduleTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.83",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsIOmoduleTest.py&quot;, line 10, in &lt;module&gt;\n    from abins import IO, test_helpers\nImportError: cannot import name &#x27;IO&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start 2214: python.MuonQt5.loadfile_view_test.loadfile_view_test\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsInstrumentTest.AbinsInstrumentTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsInstrumentTest.AbinsInstrumentTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "2.35",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsInstrumentTest.py&quot;, line 10, in &lt;module&gt;\n    from abins.instruments.instrument import Instrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/__init__.py&quot;, line 10, in &lt;module&gt;\n    from .lagrangeinstrument import LagrangeInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/lagrangeinstrument.py&quot;, line 11, in &lt;module&gt;\n    from .indirectinstrument import IndirectInstrument\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/instruments/indirectinstrument.py&quot;, line 15, in &lt;module&gt;\n    class IndirectInstrument(Instrument, abins.FrequencyPowderGenerator):\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;FrequencyPowderGenerator&#x27;\n\n          Start  802: CurveFittingTest_ThermalNeutronBk2BkExpConvPVoigtTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadCASTEPTest.AbinsLoadCASTEPTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadCASTEPTest.AbinsLoadCASTEPTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.99",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadCASTEPTest.py&quot;, line 9, in &lt;module&gt;\n    import abins.input\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 1135: GeometryTest_MDPlaneImplicitFunctionTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadCRYSTALTest.AbinsLoadCRYSTALTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadCRYSTALTest.AbinsLoadCRYSTALTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.80",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadCRYSTALTest.py&quot;, line 9, in &lt;module&gt;\n    import abins.input\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 2548: python.Calibration.test_tube.test_tube\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadDMOL3InternalsTest.AbinsLoadDMOL3InternalsTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadDMOL3InternalsTest.AbinsLoadDMOL3InternalsTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.89",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadDMOL3InternalsTest.py&quot;, line 15, in &lt;module&gt;\n    from abins.input import DMOL3Loader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 2369: MantidQtInterfacesDirectTestQt5_ALFAlgorithmManagerTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadDMOL3Test.AbinsLoadDMOL3Test",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadDMOL3Test.AbinsLoadDMOL3Test",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.73",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadDMOL3Test.py&quot;, line 9, in &lt;module&gt;\n    import abins.input\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start  141: KernelTest_VectorHelperTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadGAUSSIANTest.AbinsLoadGAUSSIANTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadGAUSSIANTest.AbinsLoadGAUSSIANTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "3.73",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadGAUSSIANTest.py&quot;, line 9, in &lt;module&gt;\n    import abins.input\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 2135: python.MuonQt5.detectors_presenter_test.detectors_presenter_test\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadPhonopyTest.AbinsLoadPhonopyTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadPhonopyTest.AbinsLoadPhonopyTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.84",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadPhonopyTest.py&quot;, line 9, in &lt;module&gt;\n    import abins.input\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 2232: python.MuonQt5.muon_group_pair_context_test.muon_group_pair_context_test\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsLoadVASPTest.AbinsLoadVASPTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsLoadVASPTest.AbinsLoadVASPTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.83",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsLoadVASPTest.py&quot;, line 10, in &lt;module&gt;\n    from abins.input import VASPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/__init__.py&quot;, line 4, in &lt;module&gt;\n    from .casteploader import CASTEPLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/casteploader.py&quot;, line 10, in &lt;module&gt;\n    from .abinitioloader import AbInitioLoader\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 23, in &lt;module&gt;\n    class AbInitioLoader(metaclass=NamedAbstractClass):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/input/abinitioloader.py&quot;, line 38, in AbInitioLoader\n    def read_vibrational_or_phonon_data(self) -&gt; abins.AbinsData:\nAttributeError: module &#x27;abins&#x27; has no attribute &#x27;AbinsData&#x27;\n\n          Start 1310: NexusGeometryTest_TubeHelpersTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsPowderCalculatorTest.AbinsPowderCalculatorTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsPowderCalculatorTest.AbinsPowderCalculatorTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.48",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsPowderCalculatorTest.py&quot;, line 12, in &lt;module&gt;\n    from abins import AbinsData, PowderCalculator\nImportError: cannot import name &#x27;AbinsData&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start  783: CurveFittingTest_ProductFunctionTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsPowderDataTest.AbinsPowderDataTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsPowderDataTest.AbinsPowderDataTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.52",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsPowderDataTest.py&quot;, line 9, in &lt;module&gt;\n    from abins import PowderData\nImportError: cannot import name &#x27;PowderData&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start 2403: MantidScientificInterfacesISISReflectometryTestQt5_QtCatalogSearcherTest\n"
            }
        },
        {
            "test_name": "python.scripts.AbinsSDataTest.AbinsSDataTest",
            "latest_failed_build": "3082",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "3087",
                    "3086",
                    "3085",
                    "3084",
                    "3083",
                    "3082",
                    "3081",
                    "3080",
                    "3079",
                    "3078",
                    "3077",
                    "3076",
                    "3075",
                    "3074",
                    "3073",
                    "3072",
                    "3071",
                    "3070",
                    "3069",
                    "3068",
                    "3067",
                    "3066",
                    "3065",
                    "3064",
                    "3063",
                    "3062",
                    "3061",
                    "3060",
                    "3059",
                    "3058"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.scripts.AbinsSDataTest.AbinsSDataTest",
                "build": "3082",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.53",
                "stacktrace": "Traceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 80, in &lt;module&gt;\n    main(sys.argv)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/testrunner.py&quot;, line 36, in main\n    test_module = SourceFileLoader(module_name(pathname), pathname).load_module()\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 522, in _check_name_wrapper\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 1022, in load_module\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 847, in load_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 265, in _load_module_shim\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 702, in _load\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 671, in _load_unlocked\n  File &quot;&lt;frozen importlib._bootstrap_external&gt;&quot;, line 843, in exec_module\n  File &quot;&lt;frozen importlib._bootstrap&gt;&quot;, line 219, in _call_with_frames_removed\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/Abins/AbinsSDataTest.py&quot;, line 15, in &lt;module&gt;\n    from abins import SData\nImportError: cannot import name &#x27;SData&#x27; from &#x27;abins&#x27; (/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/abins/__init__.py)\n\n          Start 2414: MantidScientificInterfacesISISReflectometryTestQt5_ExperimentOptionDefaultsTest\n"
            }
        }
    ]
}