{
    "data": [
        {
            "test_name": "MantidScientificInterfacesISISReflectometryTestQt5_DecoderTest",
            "latest_failed_build": "919",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 2,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidScientificInterfacesISISReflectometryTestQt5_DecoderTest",
                "build": "919",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "5.52",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221214.1711\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nRunning 12 testsSegmentation fault\n\n          Start 1518: python.algorithms.FitIncidentSpectrumTest.FitIncidentSpectrumTest\n"
            }
        },
        {
            "test_name": "MantidScientificInterfacesISISReflectometryTestQt5_EncoderTest",
            "latest_failed_build": "919",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 2,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidScientificInterfacesISISReflectometryTestQt5_EncoderTest",
                "build": "919",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "4.26",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221214.1711\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nRunning 2 testsSegmentation fault\n\n"
            }
        },
        {
            "test_name": "python.EngineeringDiffraction.test_plot_presenter.test_plot_presenter",
            "latest_failed_build": "918",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.EngineeringDiffraction.test_plot_presenter.test_plot_presenter",
                "build": "918",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "8.53",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221214.1653\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n....EEEE.........\n======================================================================\nERROR: test_do_all_fit_sets_progress_bar_to_in_progress_then_final (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 138, in test_do_all_fit_sets_progress_bar_to_in_progress_then_final\n    self.fit_all_helper(mock_fit, do_sequential=False)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_sequential_fit (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 64, in test_do_sequential_fit\n    self.fit_all_helper(mock_fit, do_sequential=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_sequential_fit_does_not_use_failed_fit_as_input (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 81, in test_do_sequential_fit_does_not_use_failed_fit_as_input\n    self.presenter.do_fit_all(ws_list, do_sequential=True)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_serial_fit (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 68, in test_do_serial_fit\n    self.fit_all_helper(mock_fit, do_sequential=False)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n----------------------------------------------------------------------\nRan 17 tests in 1.693s\n\nFAILED (errors=4)\n\n"
            }
        },
        {
            "test_name": "python.MuonQt5.corrections_view_test.corrections_view_test",
            "latest_failed_build": "916",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.MuonQt5.corrections_view_test.corrections_view_test",
                "build": "916",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "4.03",
                "stacktrace": "EEEEE\n======================================================================\nERROR: test_that_current_run_string_will_return_the_current_run_as_a_string (corrections_view_test.CorrectionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;CorrectionsView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/corrections_tab_widget/corrections_view_test.py&quot;, line 18, in setUp\n    self.view = CorrectionsView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/corrections_view.py&quot;, line 28, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 15, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_is_disabled_when_initialized (corrections_view_test.CorrectionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;CorrectionsView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/corrections_tab_widget/corrections_view_test.py&quot;, line 18, in setUp\n    self.view = CorrectionsView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/corrections_view.py&quot;, line 28, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 15, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_will_be_enabled_if_there_are_more_than_one_runs_loaded (corrections_view_test.CorrectionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;CorrectionsView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/corrections_tab_widget/corrections_view_test.py&quot;, line 18, in setUp\n    self.view = CorrectionsView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/corrections_view.py&quot;, line 28, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 15, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_will_not_be_enabled_if_there_are_no_runs_loaded (corrections_view_test.CorrectionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;CorrectionsView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/corrections_tab_widget/corrections_view_test.py&quot;, line 18, in setUp\n    self.view = CorrectionsView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/corrections_view.py&quot;, line 28, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 15, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_run_selector_combo_box_will_set_the_runs_in_the_runs_selector (corrections_view_test.CorrectionsViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;CorrectionsView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/corrections_tab_widget/corrections_view_test.py&quot;, line 18, in setUp\n    self.view = CorrectionsView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/corrections_view.py&quot;, line 28, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 15, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n----------------------------------------------------------------------\nRan 5 tests in 0.521s\n\nFAILED (errors=5)\n\n          Start 2131: python.MuonQt5.corrections_view_test.corrections_view_test\n"
            }
        },
        {
            "test_name": "MantidQtInterfacesDirectTestQt5_ALFAnalysisModelTest",
            "latest_failed_build": "897",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 3,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Failed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidQtInterfacesDirectTestQt5_ALFAnalysisModelTest",
                "build": "897",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.14",
                "stacktrace": "dyld: Symbol not found: __ZTVN8MantidQt16CustomInterfaces19ALFInstrumentWidgetE\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\nSubprocess aborted\n\n          Start 1787: PSISINQTest_PoldiCreatePeaksFromCellTest\n"
            }
        },
        {
            "test_name": "MantidQtInterfacesDirectTestQt5_ALFAnalysisPresenterTest",
            "latest_failed_build": "897",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 3,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Failed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidQtInterfacesDirectTestQt5_ALFAnalysisPresenterTest",
                "build": "897",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.14",
                "stacktrace": "dyld: Symbol not found: __ZTVN8MantidQt16CustomInterfaces19ALFInstrumentWidgetE\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\nSubprocess aborted\n\n          Start  159: AlgorithmsTest_AddSampleLogTest\n"
            }
        },
        {
            "test_name": "MantidQtInterfacesDirectTestQt5_ALFInstrumentModelTest",
            "latest_failed_build": "897",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 3,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Failed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidQtInterfacesDirectTestQt5_ALFInstrumentModelTest",
                "build": "897",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.14",
                "stacktrace": "dyld: Symbol not found: __ZTVN8MantidQt16CustomInterfaces19ALFInstrumentWidgetE\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\nSubprocess aborted\n\n          Start 1701: python.functions.AFM_LFTest.AFM_LFTest\n"
            }
        },
        {
            "test_name": "MantidQtInterfacesDirectTestQt5_ALFInstrumentPresenterTest",
            "latest_failed_build": "897",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 3,
            "past_outcome": {
                "build_keys": [
                    "924",
                    "923",
                    "922",
                    "921",
                    "920",
                    "919",
                    "918",
                    "917",
                    "916",
                    "915",
                    "914",
                    "913",
                    "912",
                    "911",
                    "910",
                    "909",
                    "908",
                    "907",
                    "906",
                    "905",
                    "904",
                    "903",
                    "902",
                    "901",
                    "900",
                    "899",
                    "898",
                    "897",
                    "896",
                    "895"
                ],
                "past_outcome_list": [
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Failed",
                    "Failed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MantidQtInterfacesDirectTestQt5_ALFInstrumentPresenterTest",
                "build": "897",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.14",
                "stacktrace": "dyld: Symbol not found: __ZTVN8MantidQt16CustomInterfaces19ALFInstrumentWidgetE\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidScientificInterfacesDirectQt5.dylib\nSubprocess aborted\n\n          Start  281: AlgorithmsTest_ExtractMaskTest\n"
            }
        }
    ]
}