{
    "data": [
        {
            "test_name": "python.IsisPowder.ISISPowderPearlTest.ISISPowderPearlTest",
            "latest_failed_build": "1891",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881",
                    "1880",
                    "1879",
                    "1878",
                    "1877",
                    "1876",
                    "1875",
                    "1874",
                    "1873",
                    "1872",
                    "1871",
                    "1870",
                    "1869",
                    "1868",
                    "1867",
                    "1866",
                    "1865"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "None",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.IsisPowder.ISISPowderPearlTest.ISISPowderPearlTest",
                "build": "1891",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "5.55",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230309.0726.dev107\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nNo config file was specified. If a configuration file  was meant to be used the path to the file is set with the &#x27;config_file&#x27; parameter.\n\nReplacing parameter: &#x27;create_cal_rebin_1_params&#x27; which was previously set to: &#x27;100,-0.0006,19950&#x27; with new value: &#x27;20300,-0.0006,39990&#x27;\nReplacing parameter: &#x27;monitor_lambda_crop_range&#x27; which was previously set to: &#x27;(0.03, 6.0)&#x27; with new value: &#x27;(5.9, 12.0)&#x27;\nReplacing parameter: &#x27;monitor_integration_range&#x27; which was previously set to: &#x27;(0.6, 5.0)&#x27; with new value: &#x27;(6, 10)&#x27;\nReplacing parameter: &#x27;raw_data_tof_cropping&#x27; which was previously set to: &#x27;(0, 19995)&#x27; with new value: &#x27;(20280, 39000)&#x27;\nReplacing parameter: &#x27;vanadium_tof_cropping&#x27; which was previously set to: &#x27;(1400, 19990)&#x27; with new value: &#x27;(20295, 39000)&#x27;\nReplacing parameter: &#x27;focused_cropping_values&#x27; which was previously set to: &#x27;[(1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900), (1500, 19900)]&#x27; with new value: &#x27;[(20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830), (20300, 38830)]&#x27;\nReplacing parameter: &#x27;custom_focused_cropping_values&#x27; which was previously set to: &#x27;(1500, 19990)&#x27; with new value: &#x27;(20300, 38830)&#x27;\nReplacing parameter: &#x27;spline_coefficient&#x27; which was previously set to: &#x27;60&#x27; with new value: &#x27;5&#x27;\nE\n======================================================================\nERROR: test_long_mode_on (ISISPowderPearlTest.ISISPowderPearlTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/test/ISISPowderPearlTest.py&quot;, line 41, in test_long_mode_on\n    inst_obj.focus(run_number=999)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/pearl.py&quot;, line 41, in focus\n    return self._focus(\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/abstract_inst.py&quot;, line 94, in _focus\n    return self._output_focused_runs(focused_runs, run_number_string)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/abstract_inst.py&quot;, line 97, in _output_focused_runs\n    run_details = self._get_run_details(run_number_string)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/pearl.py&quot;, line 108, in _get_run_details\n    tt_mode_string = self._inst_settings.tt_mode\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/routines/instrument_settings.py&quot;, line 62, in __getattr__\n    self._raise_user_param_missing_error(known_param)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/Diffraction/isis_powder/routines/instrument_settings.py&quot;, line 124, in _raise_user_param_missing_error\n    raise AttributeError(err_text)\nAttributeError: The parameter with name: &#x27;tt_mode&#x27; is required but was not set or passed.\nAcceptable values for this parameter are: all, tt35, tt70, tt88, custom\n\n----------------------------------------------------------------------\nRan 1 test in 0.007s\n\nFAILED (errors=1)\n\n          Start 1146: GeometryTest_MDPlaneImplicitFunctionTest\n"
            }
        },
        {
            "test_name": "APITest_ExperimentInfoTest",
            "latest_failed_build": "1887",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881",
                    "1880",
                    "1879",
                    "1878",
                    "1877",
                    "1876",
                    "1875",
                    "1874",
                    "1873",
                    "1872",
                    "1871",
                    "1870",
                    "1869",
                    "1868",
                    "1867",
                    "1866",
                    "1865"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "APITest_ExperimentInfoTest",
                "build": "1887",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "6.22",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230309.0726.dev86\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nDllOpen-[Error] Could not open library /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib: dlopen(/Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib, 10): Symbol not found: _PyBaseObject_Type\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\nRunning 42 tests...........................Instrument-[Warning] Saving Instrument with no XML data. If this was instrument data you may not be able to load this data back into Mantid, for fitted/analysed data this warning can be ignored.\n\nIn ExperimentInfoTest::test_nexus:\n/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/API/test/ExperimentInfoTest.h:369: Error: Test failed: Unable to parse File: in &quot;/Users/builder/.mantid/instrument/geometryCache/GEM79cd9448aebda416934e7eaafbc9acde3319724b.vtp&quot;\n/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/API/test/ExperimentInfoTest.h:369: Error: Expected (ws2.loadExperimentInfoNexus(filename, th.file.get(), parameterStr)) not to throw, but it did\n/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/API/test/ExperimentInfoTest.h:371: Error: Expected (inst-&gt;getName() == &quot;GEM&quot;), found (&quot;&quot; != GEM)\n/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/API/test/ExperimentInfoTest.h:372: Error: Assertion failed: inst-&gt;getFilename().find(&quot;GEM_Definition.xml&quot;, 0) != std::string::npos\nInstrument-[Warning] Saving Instrument with no XML data. If this was instrument data you may not be able to load this data back into Mantid, for fitted/analysed data this warning can be ignored.\n.Instrument-[Warning] Saving Instrument with no XML data. If this was instrument data you may not be able to load this data back into Mantid, for fitted/analysed data this warning can be ignored.\n.DllOpen-[Error] Could not open library /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib: dlopen(/Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib, 10): Symbol not found: _PyBaseObject_Type\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\n............\nFailed 1 of 42 tests\nSuccess rate: 97%\n\n          Start  507: APITest_ExperimentInfoTest\n"
            }
        },
        {
            "test_name": "python.kernel.MantidVersionTest.MantidVersionTest",
            "latest_failed_build": "1883",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "1894",
                    "1893",
                    "1892",
                    "1891",
                    "1890",
                    "1889",
                    "1888",
                    "1887",
                    "1886",
                    "1885",
                    "1884",
                    "1883",
                    "1882",
                    "1881",
                    "1880",
                    "1879",
                    "1878",
                    "1877",
                    "1876",
                    "1875",
                    "1874",
                    "1873",
                    "1872",
                    "1871",
                    "1870",
                    "1869",
                    "1868",
                    "1867",
                    "1866",
                    "1865"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.kernel.MantidVersionTest.MantidVersionTest",
                "build": "1883",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.81",
                "stacktrace": "..F..\n======================================================================\nFAIL: test_version_info_patch (MantidVersionTest.MantidVersionTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/__init__.py&quot;, line 87, in assertRaisesNothing\n    return callable(*args, **kwargs)\nValueError: invalid literal for int() with base 10: &#x27;20230309.0726&#x27;\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/python/mantid/kernel/MantidVersionTest.py&quot;, line 20, in test_version_info_patch\n    assertRaisesNothing(self, int, version().patch)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/test/testhelpers/__init__.py&quot;, line 89, in assertRaisesNothing\n    testobj.fail(&quot;Assertion error. An exception was caught where none was expected in %s. Message: %s&quot; % (callable.__name__, str(exc)))\nAssertionError: Assertion error. An exception was caught where none was expected in int. Message: invalid literal for int() with base 10: &#x27;20230309.0726&#x27;\n\n----------------------------------------------------------------------\nRan 5 tests in 0.002s\n\nFAILED (failures=1)\n6.6.20230309.0726.dev88\n.dev88\n\n          Start  857: DataHandlingTest_GroupDetectors2Test\n"
            }
        }
    ]
}