{
    "data": [
        {
            "test_name": "workbench.test_mantidfigurecanvas.test_mantidfigurecanvas",
            "latest_failed_build": "2687",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "2687",
                    "2686",
                    "2685",
                    "2684",
                    "2683",
                    "2682",
                    "2681",
                    "2680",
                    "2679",
                    "2678",
                    "2677",
                    "2676",
                    "2675",
                    "2674",
                    "2673",
                    "2672",
                    "2671",
                    "2670",
                    "2669",
                    "2668",
                    "2667",
                    "2666",
                    "2665",
                    "2664",
                    "2663",
                    "2662",
                    "2661",
                    "2660",
                    "2659",
                    "2658"
                ],
                "past_outcome_list": [
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "workbench.test_mantidfigurecanvas.test_mantidfigurecanvas",
                "build": "2687",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.80",
                "stacktrace": "QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to &#x27;/tmp/runtime-abc&#x27;\nF\n======================================================================\nFAIL: test_dpi_attribute_exists (test_mantidfigurecanvas.MantidFigureCanvasTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/applications/workbench/workbench/plotting/test/test_mantidfigurecanvas.py&quot;, line 19, in test_dpi_attribute_exists\n    self.assertTrue(hasattr(canvas, &quot;_dpi_ratio&quot;))\nAssertionError: False is not true\n\n----------------------------------------------------------------------\nRan 1 test in 0.027s\n\nFAILED (failures=1)\n\n          Start 2465: workbench.test_plotscriptgeneratorfigure.test_plotscriptgeneratorfigure\n"
            }
        },
        {
            "test_name": "mantidqt_qt5.test_sliceviewer_model.test_sliceviewer_model",
            "latest_failed_build": "2670",
            "agent_name": "Linux",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-linux",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "2687",
                    "2686",
                    "2685",
                    "2684",
                    "2683",
                    "2682",
                    "2681",
                    "2680",
                    "2679",
                    "2678",
                    "2677",
                    "2676",
                    "2675",
                    "2674",
                    "2673",
                    "2672",
                    "2671",
                    "2670",
                    "2669",
                    "2668",
                    "2667",
                    "2666",
                    "2665",
                    "2664",
                    "2663",
                    "2662",
                    "2661",
                    "2660",
                    "2659",
                    "2658"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "mantidqt_qt5.test_sliceviewer_model.test_sliceviewer_model",
                "build": "2670",
                "agent_name": "Linux",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "3.67",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20230127.1705.dev2\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n.....E.....EE.E...............................\n======================================================================\nERROR: test_MDH_workspace_in_hkl_supports_non_orthogonal_axes (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 402, in test_MDH_workspace_in_hkl_supports_non_orthogonal_axes\n    self._assert_supports_non_orthogonal_axes(\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 884, in _assert_supports_non_orthogonal_axes\n    model = SliceViewerModel(_create_mock_workspace(ws_type, coords, has_oriented_lattice))\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 82, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 517, in get_proj_matrix\n    i_nonq = np.flatnonzero(np.invert(qflags))\nTypeError: ufunc &#x27;invert&#x27; not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule &#x27;&#x27;safe&#x27;&#x27;\n\n======================================================================\nERROR: test_calculate_axes_angles_uses_W_if_basis_vectors_unavailable_and_W_available_MDHisto (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 540, in test_calculate_axes_angles_uses_W_if_basis_vectors_unavailable_and_W_available_MDHisto\n    model = SliceViewerModel(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 82, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 517, in get_proj_matrix\n    i_nonq = np.flatnonzero(np.invert(qflags))\nTypeError: ufunc &#x27;invert&#x27; not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule &#x27;&#x27;safe&#x27;&#x27;\n\n======================================================================\nERROR: test_calculate_axes_angles_uses_basis_vectors_even_if_WMatrix_log_available_MDHisto (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 505, in test_calculate_axes_angles_uses_basis_vectors_even_if_WMatrix_log_available_MDHisto\n    model = SliceViewerModel(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 82, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 517, in get_proj_matrix\n    i_nonq = np.flatnonzero(np.invert(qflags))\nTypeError: ufunc &#x27;invert&#x27; not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule &#x27;&#x27;safe&#x27;&#x27;\n\n======================================================================\nERROR: test_calculate_axes_angles_uses_identity_if_W_unavailable_MDHisto (test_sliceviewer_model.SliceViewerModelTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py&quot;, line 528, in test_calculate_axes_angles_uses_identity_if_W_unavailable_MDHisto\n    model = SliceViewerModel(ws)\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 82, in __init__\n    self._axes_angles = self._calculate_axes_angles()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 553, in _calculate_axes_angles\n    proj_matrix = self.get_proj_matrix()\n  File &quot;/jenkins_workdir/workspace/pull_requests-conda-linux/qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py&quot;, line 517, in get_proj_matrix\n    i_nonq = np.flatnonzero(np.invert(qflags))\nTypeError: ufunc &#x27;invert&#x27; not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule &#x27;&#x27;safe&#x27;&#x27;\n\n----------------------------------------------------------------------\nRan 46 tests in 0.771s\n\nFAILED (errors=4)\n\n          Start  369: AlgorithmsTest_MultiplyRangeTest\n"
            }
        }
    ]
}